ln -s . parasail_sources_$1
zip -u parasail_sources_$1.zip \
parasail_sources_$1/interpreter/*.ad? \
parasail_sources_$1/interpreter/config.sh \
parasail_sources_$1/parser/*.ad? \
parasail_sources_$1/parser/*.[yl] \
parasail_sources_$1/parser/gen/*.ad? \
parasail_sources_$1/sparkel_parser/*.ad? \
parasail_sources_$1/sparkel_parser/*.[yl] \
parasail_sources_$1/sparkel_parser/gen/*.ad? \
parasail_sources_$1/javallel_parser/*.ad? \
parasail_sources_$1/javallel_parser/*.[yl] \
parasail_sources_$1/javallel_parser/gen/*.ad? \
parasail_sources_$1/parython_parser/*.ad? \
parasail_sources_$1/parython_parser/*.[yl] \
parasail_sources_$1/parython_parser/gen/*.ad? \
parasail_sources_$1/semantics/*.ad? \
parasail_sources_$1/examples/math.psl \
parasail_sources_$1/examples/hello_gtk.psl \
parasail_sources_$1/examples/hello_button.psl \
parasail_sources_$1/examples/tic_tac_toe_gtk.psl \
parasail_sources_$1/examples/imat_vec.psl \
parasail_sources_$1/examples/main_drinking_phils.psl \
parasail_sources_$1/bin/*sh \
parasail_sources_$1/lib/*.ps? \
parasail_sources_$1/lib/aaa/{*.ps?,*sh} \
parasail_sources_$1/lib/aaa/*.ps?.ll \
parasail_sources_$1/Makefile \
parasail_sources_$1/build/*.gpr \
parasail_sources_$1/design/*.txt \
parasail_sources_$1/parser/build/Makefile \
parasail_sources_$1/sparkel_parser/build/Makefile \
parasail_sources_$1/javallel_parser/build/Makefile \
parasail_sources_$1/parython_parser/build/Makefile \
parasail_sources_$1/documentation/COPYING3 \
parasail_sources_$1/documentation/parasail_intro.pdf \
parasail_sources_$1/documentation/ref_manual/ \
parasail_sources_$1/documentation/ref_manual/Makefile \
parasail_sources_$1/documentation/ref_manual/parasail_ref_manual.ltx \
parasail_sources_$1/documentation/ref_manual/parasail_ref_manual.pdf \
parasail_sources_$1/documentation/sparkel_ref_manual/ \
parasail_sources_$1/documentation/sparkel_ref_manual/Makefile \
parasail_sources_$1/documentation/sparkel_ref_manual/sparkel_ref_manual.ltx \
parasail_sources_$1/documentation/sparkel_ref_manual/sparkel_ref_manual.pdf \
parasail_sources_$1/documentation/parasail_release_notes.txt \
parasail_sources_$1/documentation/sparkel_release_notes*.txt \
parasail_sources_$1/aflex_ayacc/aflex/ \
parasail_sources_$1/aflex_ayacc/aflex/aflex.adb \
parasail_sources_$1/aflex_ayacc/aflex/aflex_command_line_interface.adb \
parasail_sources_$1/aflex_ayacc/aflex/aflex_command_line_interface.ads \
parasail_sources_$1/aflex_ayacc/aflex/aflex_misc.adb \
parasail_sources_$1/aflex_ayacc/aflex/aflex_misc.ads \
parasail_sources_$1/aflex_ayacc/aflex/aflex_scanner.adb \
parasail_sources_$1/aflex_ayacc/aflex/aflex_scanner.ads \
parasail_sources_$1/aflex_ayacc/aflex/ascan.l \
parasail_sources_$1/aflex_ayacc/aflex/ccl.adb \
parasail_sources_$1/aflex_ayacc/aflex/ccl.ads \
parasail_sources_$1/aflex_ayacc/aflex/COPYRIGHT \
parasail_sources_$1/aflex_ayacc/aflex/dfa.adb \
parasail_sources_$1/aflex_ayacc/aflex/dfa.ads \
parasail_sources_$1/aflex_ayacc/aflex/ecs.adb \
parasail_sources_$1/aflex_ayacc/aflex/ecs.ads \
parasail_sources_$1/aflex_ayacc/aflex/external_file_manager.adb \
parasail_sources_$1/aflex_ayacc/aflex/external_file_manager.ads \
parasail_sources_$1/aflex_ayacc/aflex/file_string.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/ \
parasail_sources_$1/aflex_ayacc/aflex/GEN/aflex_parser.adb \
parasail_sources_$1/aflex_ayacc/aflex/GEN/aflex_parser.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/ascan_dfa.adb \
parasail_sources_$1/aflex_ayacc/aflex/GEN/ascan_dfa.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/ascan_io.adb \
parasail_sources_$1/aflex_ayacc/aflex/GEN/ascan_io.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/parse_goto.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/parse_shift_reduce.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/parse_tokens.ads \
parasail_sources_$1/aflex_ayacc/aflex/GEN/scanner.adb \
parasail_sources_$1/aflex_ayacc/aflex/GEN/scanner.ads \
parasail_sources_$1/aflex_ayacc/aflex/gen.adb \
parasail_sources_$1/aflex_ayacc/aflex/gen.ads \
parasail_sources_$1/aflex_ayacc/aflex/int_io.ads \
parasail_sources_$1/aflex_ayacc/aflex/main_body.adb \
parasail_sources_$1/aflex_ayacc/aflex/main_body.ads \
parasail_sources_$1/aflex_ayacc/aflex/misc_defs.adb \
parasail_sources_$1/aflex_ayacc/aflex/misc_defs.ads \
parasail_sources_$1/aflex_ayacc/aflex/nfa.adb \
parasail_sources_$1/aflex_ayacc/aflex/nfa.ads \
parasail_sources_$1/aflex_ayacc/aflex/parse.y \
parasail_sources_$1/aflex_ayacc/aflex/skeleton_manager.adb \
parasail_sources_$1/aflex_ayacc/aflex/skeleton_manager.ads \
parasail_sources_$1/aflex_ayacc/aflex/sym.adb \
parasail_sources_$1/aflex_ayacc/aflex/sym.ads \
parasail_sources_$1/aflex_ayacc/aflex/tblcmp.adb \
parasail_sources_$1/aflex_ayacc/aflex/tblcmp.ads \
parasail_sources_$1/aflex_ayacc/aflex/template_manager.adb \
parasail_sources_$1/aflex_ayacc/aflex/template_manager.ads \
parasail_sources_$1/aflex_ayacc/aflex/tstring.ads \
parasail_sources_$1/aflex_ayacc/aflex/vstrings.adb \
parasail_sources_$1/aflex_ayacc/aflex/vstrings.ads \
parasail_sources_$1/aflex_ayacc/ayacc/ \
parasail_sources_$1/aflex_ayacc/ayacc/actions_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/actions_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc-initialize-get_arguments.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc-initialize.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc-print_statistics.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc_file_names.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ayacc_file_names.ads \
parasail_sources_$1/aflex_ayacc/ayacc/command_line_interface-read_command_line.adb \
parasail_sources_$1/aflex_ayacc/ayacc/command_line_interface.adb \
parasail_sources_$1/aflex_ayacc/ayacc/command_line_interface.ads \
parasail_sources_$1/aflex_ayacc/ayacc/COPYRIGHT \
parasail_sources_$1/aflex_ayacc/ayacc/error_report_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/error_report_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/goto_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/goto_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/lalr_symbol_info.adb \
parasail_sources_$1/aflex_ayacc/ayacc/lalr_symbol_info.ads \
parasail_sources_$1/aflex_ayacc/ayacc/lexical_analyzer.adb \
parasail_sources_$1/aflex_ayacc/ayacc/lexical_analyzer.ads \
parasail_sources_$1/aflex_ayacc/ayacc/lists.adb \
parasail_sources_$1/aflex_ayacc/ayacc/lists.ads \
parasail_sources_$1/aflex_ayacc/ayacc/lr0_machine.adb \
parasail_sources_$1/aflex_ayacc/ayacc/lr0_machine.ads \
parasail_sources_$1/aflex_ayacc/ayacc/options.adb \
parasail_sources_$1/aflex_ayacc/ayacc/options.ads \
parasail_sources_$1/aflex_ayacc/ayacc/output_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/output_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/parse_table.adb \
parasail_sources_$1/aflex_ayacc/ayacc/parse_table.ads \
parasail_sources_$1/aflex_ayacc/ayacc/parse_template_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/parse_template_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/parser.adb \
parasail_sources_$1/aflex_ayacc/ayacc/parser.ads \
parasail_sources_$1/aflex_ayacc/ayacc/ragged.adb \
parasail_sources_$1/aflex_ayacc/ayacc/ragged.ads \
parasail_sources_$1/aflex_ayacc/ayacc/rule_table.adb \
parasail_sources_$1/aflex_ayacc/ayacc/rule_table.ads \
parasail_sources_$1/aflex_ayacc/ayacc/set_pack.adb \
parasail_sources_$1/aflex_ayacc/ayacc/set_pack.ads \
parasail_sources_$1/aflex_ayacc/ayacc/shift_reduce_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/shift_reduce_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/source_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/source_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/stack_pack.adb \
parasail_sources_$1/aflex_ayacc/ayacc/stack_pack.ads \
parasail_sources_$1/aflex_ayacc/ayacc/stack_pkg.adb \
parasail_sources_$1/aflex_ayacc/ayacc/stack_pkg.ads \
parasail_sources_$1/aflex_ayacc/ayacc/str_pack.adb \
parasail_sources_$1/aflex_ayacc/ayacc/str_pack.ads \
parasail_sources_$1/aflex_ayacc/ayacc/string_lists.ads \
parasail_sources_$1/aflex_ayacc/ayacc/string_pkg.adb \
parasail_sources_$1/aflex_ayacc/ayacc/string_pkg.ads \
parasail_sources_$1/aflex_ayacc/ayacc/string_scanner.adb \
parasail_sources_$1/aflex_ayacc/ayacc/string_scanner.ads \
parasail_sources_$1/aflex_ayacc/ayacc/symbol_info.adb \
parasail_sources_$1/aflex_ayacc/ayacc/symbol_info.ads \
parasail_sources_$1/aflex_ayacc/ayacc/symbol_table.adb \
parasail_sources_$1/aflex_ayacc/ayacc/symbol_table.ads \
parasail_sources_$1/aflex_ayacc/ayacc/tokens_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/tokens_file.ads \
parasail_sources_$1/aflex_ayacc/ayacc/verbose_file.adb \
parasail_sources_$1/aflex_ayacc/ayacc/verbose_file.ads \
parasail_sources_$1/share/tools/*.* \
parasail_sources_$1/share/tools/vi_tags/* \
parasail_sources_$1/sparkel_examples/*.sk? \
parasail_sources_$1/sparkel_examples/_do*sh \
parasail_sources_$1/javallel_examples/*.jl? \
parasail_sources_$1/parython_examples/*.pr? \
parasail_sources_$1/parython_examples/_do*sh \
parasail_sources_$1/share/sparkel_tools/geshi_sparkel.php \
parasail_sources_$1/share/contrib/kmeans*/{README,*.ps?,*.json} \
parasail_sources_$1/testsuite/support/{*.sh,*.gpr} \
parasail_sources_$1/testsuite/*.txt \
parasail_sources_$1/testsuite/{ParaSail,Sparkel,Javallel,Parython}/*/{*.sh,*.out,*.opt} \
parasail_sources_$1/testsuite/ParaSail/*/*.ps? \
parasail_sources_$1/testsuite/Sparkel/*/*.sk? \
parasail_sources_$1/testsuite/Javallel/*/*.jl? \
parasail_sources_$1/testsuite/Parython/*/*.pr? \

rm parasail_sources_$1
ln -s _release parasail_sources_$1
zip -u parasail_sources_$1.zip parasail_sources_$1/examples/*.ps?
rm parasail_sources_$1
